### ISSUE TITLE
RuntimeError: CUDA error: uncorrectable ECC error encountered on gpu7 (H100) 

### ISSUE THREAD

**Issue by orensg1** [StarHPC/Issues#7]
### Code of Conduct

- [X] I have read and agree to Star HPC's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem?

When trying to use gpu7 it reports: 
`RuntimeError: CUDA error: uncorrectable ECC error encountered`

### Steps to Reproduce

Install python environment with pytorch using conda: `https://pytorch.org/get-started/locally/`

Run the following code:
```
import torch
print(torch.__version__)
print(torch.cuda.get_device_properties(0))
print(torch.randn(1, device="cuda"))
```

Example run:
```
[h702533437@gpu7 tests]$ conda activate pt-3.10
(pt-3.10) [h702533437@gpu7 tests]$ python --version
Python 3.10.4
(pt-3.10) [h702533437@gpu7 tests]$ python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>
>>> print(torch.__version__)
2.0.1
>>> print(torch.cuda.get_device_properties(0))
_CudaDeviceProperties(name='NVIDIA H100 80GB HBM3', major=9, minor=0, total_memory=81230MB, multi_processor_count=132)
>>>
>>> print(torch.randn(1, device="cuda"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

>>> exit()
(pt-3.10) [h702533437@gpu7 tests]$ export CUDA_LAUNCH_BLOCKING=1
(pt-3.10) [h702533437@gpu7 tests]$ python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.0.1
>>>  print(torch.randn(1, device="cuda"))
  File "<stdin>", line 1
    print(torch.randn(1, device="cuda"))
IndentationError: unexpected indent
>>> print(torch.randn(1, device="cuda"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: uncorrectable ECC error encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`
```

### Expected Results

The code should run without an error

### Additional information

It might be a hardware issue but this could be the result of an old nvidia driver. 
I recommend to try to upgrade the beta driver as we discussed on Discord.

**Comment by MKhlystun** [comment]
I could not reproduce the issue with Python 3.9 after upgrading Nvidia driver.
```
module add jupyter/14.3.0
[mkhlystun@gpu7 github_issue_7]$ source .venv/bin/activate
(.venv) [mkhlystun@gpu7 github_issue_7]$ python tset.py
/home/mkhlystun/github_issue_7/.venv/lib/python3.9/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
2.6.0+cu124
_CudaDeviceProperties(name='NVIDIA H100 80GB HBM3', major=9, minor=0, total_memory=81105MB, multi_processor_count=132, uuid=df0d35d0-2e36-f241-aeaa-7ccea51c2ea9, L2_cache_size=50MB)
tensor([0.8685], device='cuda:0')
```
